export const pokemonList = [
    { "id": 1, "type": "Fire", "name": "Charizard" },
    { "id": 2, "type": "Water", "name": "Blastoise" },
    { "id": 3, "type": "Grass", "name": "Venusaur" },
    { "id": 4, "type": "Electric", "name": "Pikachu" },
    { "id": 5, "type": "Psychic", "name": "Alakazam" },
    { "id": 6, "type": "Fighting", "name": "Machamp" },
    { "id": 7, "type": "Rock", "name": "Onix" },
    { "id": 8, "type": "Ghost", "name": "Gengar" },
    { "id": 9, "type": "Ice", "name": "Lapras" },
    { "id": 10, "type": "Dragon", "name": "Dragonite" },
    { "id": 11, "type": "Dark", "name": "Umbreon" },
    { "id": 12, "type": "Steel", "name": "Metagross" },
    { "id": 13, "type": "Fairy", "name": "Gardevoir" },
    { "id": 14, "type": "Bug", "name": "Scizor" },
    { "id": 15, "type": "Ground", "name": "Garchomp" },
    { "id": 16, "type": "Flying", "name": "Pidgeot" },
    { "id": 17, "type": "Normal", "name": "Snorlax" },
    { "id": 18, "type": "Poison", "name": "Nidoking" },
    { "id": 19, "type": "Grass", "name": "Sceptile" },
    { "id": 20, "type": "Fire", "name": "Infernape" },
    { "id": 21, "type": "Electric", "name": "Jolteon" },
    { "id": 22, "type": "Water", "name": "Gyarados" },
    { "id": 23, "type": "Psychic", "name": "Espeon" },
    { "id": 24, "type": "Dragon", "name": "Salamence" },
    { "id": 25, "type": "Ghost", "name": "Chandelure" },
    { "id": 26, "type": "Steel", "name": "Lucario" },
    { "id": 27, "type": "Ground", "name": "Swampert" },
    { "id": 28, "type": "Bug", "name": "Heracross" },
    { "id": 29, "type": "Normal", "name": "Eevee" },
    { "id": 30, "type": "Ice", "name": "Glaceon" }
  ];
  